// Smdn.Text.Ondulish.Dictionaries.dll (Smdn.Text.Ondulish.Dictionaries-4.0.2)
//   Name: Smdn.Text.Ondulish.Dictionaries
//   AssemblyVersion: 4.0.2.0
//   InformationalVersion: 4.0.2+fdb4c8a0ea00389c28b39c7a913639e82b2c9e1f
//   TargetFramework: .NETStandard,Version=v2.0
//   Configuration: Release
//   Referenced assemblies:
//     netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
//   Embedded resources:
//     Smdn.Text.Ondulish.Dictionaries.phrases (5,670 bytes, Embedded, ContainedInManifestFile)
//     Smdn.Text.Ondulish.Dictionaries.words (2,231 bytes, Embedded, ContainedInManifestFile)
#nullable enable annotations

using System.IO;

namespace Smdn.Text.Ondulish {
  public static class OndulishDictionaries {
    public static Stream OpenPhraseDictionaryStream() {}
    public static Stream OpenWordDictionaryStream() {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.2.1.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.2.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
