// Smdn.Text.Ondulish.Dictionaries.dll (Smdn.Text.Ondulish.Dictionaries-4.1.0)
//   Name: Smdn.Text.Ondulish.Dictionaries
//   AssemblyVersion: 4.1.0.0
//   InformationalVersion: 4.1.0+03f779090fe8f75585cc1750ae1d8fc9f650a641
//   TargetFramework: .NETCoreApp,Version=v6.0
//   Configuration: Release
//   Referenced assemblies:
//     System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//   Embedded resources:
//     Smdn.Text.Ondulish.Dictionaries.phrases (5,670 bytes, Embedded, ContainedInManifestFile)
//     Smdn.Text.Ondulish.Dictionaries.words (2,231 bytes, Embedded, ContainedInManifestFile)
#nullable enable annotations

using System.IO;

namespace Smdn.Text.Ondulish {
  public static class OndulishDictionaries {
    public static Stream OpenPhraseDictionaryStream() {}
    public static Stream OpenWordDictionaryStream() {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.4.0.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.3.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
