// Smdn.Text.Ondulish.Dictionaries.dll (Smdn.Text.Ondulish.Dictionaries-4.0.1)
//   Name: Smdn.Text.Ondulish.Dictionaries
//   AssemblyVersion: 4.0.1.0
//   InformationalVersion: 4.0.1+c1dd603eda752a0663a70ade3b4ffbc85061ba78
//   TargetFramework: .NETStandard,Version=v2.0
//   Configuration: Release
//   Referenced assemblies:
//     netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
//   Embedded resources:
//     Smdn.Text.Ondulish.Dictionaries.phrases (5,027 bytes, Embedded, ContainedInManifestFile)
//     Smdn.Text.Ondulish.Dictionaries.words (2,002 bytes, Embedded, ContainedInManifestFile)
#nullable enable annotations

using System.IO;

namespace Smdn.Text.Ondulish {
  public static class OndulishDictionaries {
    public static Stream OpenPhraseDictionaryStream() {}
    public static Stream OpenWordDictionaryStream() {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.2.1.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.2.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
